### PR TITLE
Fix invalid hashes with least possible disruptions

### LINKED ISSUE #8: Hash algorithm buggy
### Problem

__`Iqons._hash` is really buggy.__
In short, it generates a formatted decimal number (as string) from a text but returns `%.1f` instead of `%013.1f`.

The code that uses the hash always assumes the string length to be 15 (13 places left of the comma), when in reality it's 14 with a 10% chance, 13 with a 1% chance, 12 with 0.1%, and so on.

This is an issue because the code takes the characters (digits) of the hash and recombines them to new numbers that serve as indices etc. It's especially painful for the naming concept #6.

Example of bad hash
 - Pre-image `NQ99 1PRP 7BR3 KFS2 H3KK R5E7 CXB5 T9QT AC11`
 - Hash `91471325.3`
 - Length is 10 instead of 15
 - Chance of encountering len 10 in the wild: 0,001% or every 100k addresses 
 - Three digits are missing (past string end) and one is set to `.`
 - __amputated bottom__ (no bottom index)
 - __black accent__ (no accent index)

Test [here](https://nimiq.github.io/iqons/).

image

Note that this is different from [bottom-10](https://nimiq.github.io/iqons/catalog.html), which is the floating Iqon.

## Fixes

I have three suggestions on how to fix it

#### Suggestion 1: 

 - The number should always be 13 characters long
 - There should be no decimal places and decimal separator
 - ~~Leading~~ _Trailing_  zeros should be used to increase length _(multiply by 10)_
 - __But:__ There is a _(edit) less than_ 9 in 100 chance that an existing Iqon changes

#### Suggestion 2:

 - Avoid converting to strings and back to numbers in the code
 - Use modulo instead
 - Again, 9 in 100 chance to modify an Iqon

#### Suggestion 3:

 - Switch to correct and stable hash algorithm like CRC32
 - All Iqons will be modified

### PR DESCRIPTION
**Pull request by sisou**
Resolves #8.

A small percentage of returned values are actually too short, to an invalid bottom index and feature color. Adding creates a bottom feature and feature color where existed previously, thus it's not a disrupting change.

The change was tested, and does not interfere with most of the identicons. Only identicons which were missing features or colors previously are now changed (fixed).

### CODE REVIEW

**Review by danimoh — CHANGES_REQUESTED** [review]
Replacing the the `.` with zero and filling up with zeros introduces a bias towards the assets / colors with these ids.
Why not run another round of `_hash` on the calculated string and use the result for fill up?

File: src/js/iqons.js [hunk 1]
```diff
@@ -205,7 +205,7 @@ ${ content }
         if (!!String.prototype.padEnd) return string.padEnd(maxLength, fillString);
         else {
             while (string.length < maxLength) string += fillString;
-            return string;
+            return string.substr(0, maxLength);
```
Comment (danimoh) [inline src/js/iqons.js]: That's not how the native `padEnd` behaves.
Also `substr` is a legacy function. Use `substring` instead.

File: src/js/iqons.js [hunk 2]
```diff
@@ -169,20 +169,22 @@ ${ content }
...
                 .map(c => Number(c.charCodeAt(0)) + 3)
                 .reduce((a, e) => a * (1 - a) * this.__chaosHash(e), 0.5))
             .split('')
-            .reduce((a, e) => e + a, '')
-            .substr(4, 17)
-            .replace('.', '0'); // A dot cannot be parsed into an int
+            .reduce((a, e) => e + a, '');
+
+        const hash = fullHash
+            .replace('.', fullHash[5]) // Replace the dot as it cannot be parsed to int
```
Comment (danimoh) [inline src/js/iqons.js:180]: Comment about why `fullHash[5]` is used would be good.

Also could `fullHash[5]` also be a `.` if we're unlucky?

Not using same `fullHash[5]` for the dot and all pad positions would ensure a greater variability.

**Review by danimoh — CHANGES_REQUESTED** [review]

File: src/js/iqons.js (hunk 2 above)
Comment (riptl) [reply src/js/iqons.js:180]: Yes, the number could even be `0.23582...` if we're unlucky.
I did some testing and it seems like larger strings generate larger numbers though.
So hashing the hash again might cause problems.

Comment (riptl) [reply src/js/iqons.js:180]: The chance of `fullHash[5]` being `.` is probably something like 1 in 100 million
